#!/bin/bash
set -e
echo "Install thousands of dependencies ..."
if type apt-get;then
	apt-get install -y ipython vim python-setuptools python-dev build-essential
elif type yum;then
	yum install -y ipython vim python-setuptools
	yum groupinstall -y 'Development Tools'
	yum groupinstall -y 'Development Libraries'	
else
	echo "Can't find package manager"
	exit 1
fi

echo "Install python dependencies for bunched plugins:"
easy_install nose nose_machineout vim_bridge 
