#!/bin/bash

set -e

DIR=`dirname $0`
VAM="vam-setup.vim"
PLUGINS="plugins.vim"
SETTINGS="settings.vim"

sudo "$DIR/install_dependencies"

cp "$DIR/$VAM" ~/

cp "$DIR/$PLUGINS" ~/

cp ~/.vimrc ~/vimrc-original || true

echo "Should I merge existing .vimrc with vam setup, or simply replace it?"
select result in "Merge" "Replace"
do
	case $result in
		Merge) 
			cat ~/.vimrc >> ~/$PLUGINS;
			break;;
		Replace)
			break;;
	esac
done

mv ~/$PLUGINS ~/.vimrc

echo "" >> ~/.vimrc
echo "" >> ~/.vimrc
cat "$DIR/$SETTINGS" >> ~/.vimrc

if [ -d ~/.vim ];then
	echo "Moving ~/.vim to ~/.vim.old"
	mv ~/.vim ~/.vim.old
fi

#Install all plugins using VAM
vim
